#pragma config(Motor,  port1,           Descorer,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           DriveLeft1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveLeft2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveRight1,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           DriveRight2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Indexer,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Flywheel1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Flywheel2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Flywheel3,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/

/*                                                                        */

/*      Description: Competition template for VEX EDR                   */

/*                                                                        */

/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform

#pragma platform(VEX2)

// Select Download method as "competition"

#pragma competitionControl(Competition)

//Main competition background code...do not modify!

#include "Vex_Competition_Includes.c"
#define min(a, b) (a) < (b) ? (a) : (b)
#define max(a, b) (a) < (b) ? (b) : (a)

// Global variables

const int dev = -10; // Global deviation
int con = -1; // Conventional direction
bool stop_intake; // For stopping ball-intake
bool holding;
bool flags; // For when we're on the flags side during autonomous
bool red; // For when we're on the red side during autonomous


/*---------------------------------------------------------------------------*/

/*                        Pre-Autonomous Functions                      */

/*                                                                        */

/*  You may want to perform some actions before the competition starts.   */

/*  Do them in the following function.  You must return from this function   */

/*  or the autonomous and usercontrol tasks will not be started.  This    */

/*  function is only called once after the cortex has been powered on and */

/*  not every time that the robot is disabled.                            */

/*---------------------------------------------------------------------------*/

void pre_auton () {

  // Set bStopTasksBetweenModes to false if you want to keep user created tasks

  // running between Autonomous and Driver controlled modes. You will need to

  // manage all user created tasks if set to false.

  bStopTasksBetweenModes = true;

  // Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD

  // used by the competition include file, for example, you might want

  // to display your team name on the LCD in this function.

  // bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts

  // Example: clearing encoders, setting servo positions, ...

  return;

}



// Global helper functions



// For stopping the drive
void StopDrive () {
  motor[DriveLeft1] = motor[DriveRight1] = motor[DriveRight2] = motor[DriveLeft2] = 0;
}

// For stopping the shooter
void StopShoot () {
  motor[Flywheel1] = motor[Flywheel2] = 0;
  motor[Flywheel3] = 0;
}

// For stopping the claw flipper
void StopDescorer () {
  motor[Descorer] = 0;
}

// For stopping the ball intake
void StopBallIntake () {
  motor[Intake] = 0;
}

void StopBallIndexer () {
	motor[Indexer] = 0;
}

// Drive forward
void DriveF (int amount, int time) {
  int tmp = amount;
  motor[DriveLeft1] = tmp * -con;
  motor[DriveRight1] = tmp * -con - dev;
  motor[DriveRight2] = tmp * -con - dev;
  motor[DriveLeft2] = tmp * -con;
  if (time != 0) wait1Msec(time);
}

// Drive backwards
void DriveB (int amount, int time) {
  int tmp = -amount;
  motor[DriveLeft1] = tmp * -con;
  motor[DriveRight1] = tmp * -con - dev;
  motor[DriveRight2] = tmp * -con - dev;
  motor[DriveLeft2] = tmp * -con;
  if (time != 0) wait1Msec(time);
}

// Turn right
void TurnR (int amount, int time) {
  motor[DriveLeft1] = amount * -con;
  motor[DriveRight1] = -amount * -con;
  motor[DriveRight2] = -amount * -con;
  motor[DriveLeft2] = amount * -con;
  if (time != 0) wait1Msec(time);
}

// Turn left
void TurnL (int amount, int time) {
  motor[DriveLeft1] = amount * con;
  motor[DriveRight1] = -amount * con;
  motor[DriveRight2] = -amount * con;
  motor[DriveLeft2] = amount * con;
  if (time != 0) wait1Msec(time);
}

void Turn90L () {
	TurnL(100, 150);
}

void Turn90R () {
	TurnR(100, 550);
}

// For taking ball in
task BallIntake1 () {
  motor[Intake] = -100 * con;
}


// For taking ball out
task BallIntake2 () {
  motor[Intake] = 100 * con;
}

// Turns both the indexer and loader one way
task Indexer1 () {
	motor[Indexer] = 100 * -con;
}

// Turns both the indexer and loader the other way
task Indexer2 () {
	motor[Indexer] = -100 * -con;
}

// Turns both the intake and indexer and loader
task Loader1 () {
	motor[Intake] = motor[Indexer] = 100 * -con;
}

// For shooting the ball up - automate it for now
task Shoot () {
	// Change value of 100 if needed
  motor[Flywheel1] = motor[Flywheel2] = 127 * -con;
  motor[Flywheel3] = -127 * -con;
	startTask(Indexer1);
	wait1Msec(500);
	stopTask(Indexer1);
}

// Auto shoots the balls onto the top 2 flags
void autoShoot () {
	startTask(Shoot);
	stopTask(Shoot);
	StopShoot();
	wait1Msec(500);//WAIT BEFORE DRIVING FOROWRD
	DriveF(100, 500);
	StopDrive();
	startTask(Shoot);
	stopTask(Shoot);
	StopShoot();
}

// Rotate the claw to flip the object
void DescorerUp (int amount, int time) {

  motor[Descorer] = amount * con;

  if (time != 0) wait1Msec(time);

}

void DescorerDown (int amount, int time) {

  motor[Descorer] = amount * -con;

  if (time != 0) wait1Msec(time);

}

/*---------------------------------------------------------------------------*/

/*                                                                        */

/*                            Autonomous Task                           */

/*                                                                        */

/*  This task is used to control your robot during the autonomous phase of   */

/*  a VEX Competition.                                                    */

/*                                                                        */

/*  You must modify the code to add your own robot specific commands here.   */

/*---------------------------------------------------------------------------*/



// Autonomous Functions



// For when we are on the side with no flags during autonomous

void autoWithFlags (bool red) {
  // Red side
  if (red) {
			// Drive up to get the ball underneath the cap
			DriveF(100, 500);
			StopDrive();
  		// Load the ball into the intake
  		startTask(BallIntake1);
  		startTask(Indexer1);
  		wait1Msec(1000);
  		stopTask(BallIntake1);
  		stopTask(Indexer1);

  		// Drive back and rotate 90 degrees CCW
  		DriveB(100, 500);
  		StopDrive();
  		Turn90L();
  		StopDrive();

  		/* Can alternatively use autoShoot() instead of code below */

  		// Shoot the ball onto the top flag
  		startTask(Shoot);
  		wait1Msec(500);
  		// Stop flywheel and drive up then stop drive
  		StopShoot();
  		DriveF(100, 50);
  		StopDrive();
  		// Turn on flywheel to shoot middle flag
  		startTask(Shoot);
  		wait1Msec(500);
  		// Turn off flywheel and drive straight to toggle low flag
  		StopShoot();


  		DriveF(100, 100);
  		StopDrive();
  		// Drive back and turn 90 degrees CW
  		DriveB(100, 100);
  		StopDrive();
  		Turn90R();
  		StopDrive();
  		// Flip over the cap/drive forwards simultaneously
  		startTask(BallIntake2);
  		DriveF(100, 100);
  		StopDrive();
  		stopTask(BallIntake2);
  		// Drive back and turn 90 degrees CW
  		DriveB(100, 250);
  		StopDrive();
  		Turn90R();
  		StopDrive();
  		// Drive forwards to get onto the platform
  		DriveF(100, 200);
  		StopDrive();
  		// Turn 90 degrees CCW and drive onto the platform
			Turn90L();
			StopDrive();
			DriveF(100, 1000);
			StopDrive();
  }

  // Blue side (left and right are flipped)

  else {
			// Drive up to get the ball underneath the cap
			DriveF(100, 500);
			StopDrive();
  		// Load the ball into the intake
  		startTask(BallIntake1);
  		startTask(Indexer1);
  		wait1Msec(1000);
  		stopTask(BallIntake1);
  		stopTask(Indexer1);

  		// Drive back and rotate 90 degrees CW
  		DriveB(100, 500);
  		StopDrive();
  		Turn90R();
  		StopDrive();

  		/* Can alternatively use autoShoot() instead of code below */

  		// Shoot the ball onto the top flag
  		startTask(Shoot);
  		wait1Msec(500);
  		// Stop flywheel and drive up then stop drive
  		StopShoot();
  		DriveF(100, 50);
  		StopDrive();
  		// Turn on flywheel to shoot middle flag
  		startTask(Shoot);
  		wait1Msec(500);
  		// Turn off flywheel and drive straight to toggle low flag
  		StopShoot();


  		DriveF(100, 100);
  		StopDrive();
  		// Drive back and turn 90 degrees CCW
  		DriveB(100, 100);
  		StopDrive();
  		Turn90L();
  		StopDrive();
  		// Flip over the cap/drive forwards simultaneously
  		startTask(BallIntake2);
  		DriveF(100, 100);
  		StopDrive();
  		stopTask(BallIntake2);
  		// Drive back and turn 90 degrees CCW
  		DriveB(100, 250);
  		StopDrive();
  		Turn90L();
  		StopDrive();
  		// Drive forwards to get onto the platform
  		DriveF(100, 200);
  		StopDrive();
  		// Turn 90 degrees CW and drive onto the platform
			Turn90R();
			StopDrive();
			DriveF(100, 1000);
			StopDrive();
  }
}

// For when we are on the side with flags during autonomous
void autoNoFlags (bool red) {

  // Red side
  if (red) {
  		// Drive straight to align with the opponent's cap
  		DriveF(100, 100);
  		StopDrive();

  		// Turn 90 degrees CCW and drive forwards, while turning on ball intake, to flip over the cap
  		Turn90L();
  		StopDrive();
  		startTask(BallIntake2);
			DriveF(100, 500);
			stopTask(BallIntake2);

  		// Now drive back and turn 90 degrees CCW
  		DriveB(100, 400);
  		StopDrive();
			Turn90L();
			StopDrive();

  		// Drive forwards and turn 90 degrees CW to align with the platform
  		DriveF(100, 100);
  		StopDrive();
  		Turn90R();
  		StopDrive();

  		// Now drive forwards to get onto the platform
    	DriveF(100, 1000);
    	StopDrive();
  }

  // Blue side (left and right are flipped)
  else {
			// Drive straight to align with the opponent's cap
  		DriveF(100, 100);
  		StopDrive();

  		// Turn 90 degrees CW and drive forwards, while turning on ball intake, to flip over the cap
  		Turn90R();
  		StopDrive();
  		startTask(BallIntake2);
			DriveF(100, 500);
			stopTask(BallIntake2);

  		// Now drive back and turn 90 degrees CW
  		DriveB(100, 400);
  		StopDrive();
			Turn90R();
			StopDrive();

  		// Drive forwards and turn 90 degrees CCW to align with the platform
  		DriveF(100, 100);
  		StopDrive();
  		Turn90L();
  		StopDrive();

  		// Now drive forwards to get onto the platform
    	DriveF(100, 1000);
    	StopDrive();
  }

}


task autonomous () {
  // ..........................................................................

  // Insert user code here.

  // ..........................................................................

  // Still needs TESTING

  if (flags) {
    autoWithFlags(red);
  }
  else {
    autoNoFlags(red);
  }
}



/*---------------------------------------------------------------------------*/

/*                                                                        */

/*                            User Control Task                         */

/*                                                                        */

/*  This task is used to control your robot during the user control phase of */

/*  a VEX Competition.                                                    */

/*                                                                        */

/*  You must modify the code to add your own robot specific commands here.   */

/*---------------------------------------------------------------------------*/



task usercontrol () {

  // User control code here, inside the loop
  while (1) {
    // FORWARD AND BACKWARD
    int tmp = 0;

    if (vexRT[Ch2] > 20) {
      tmp = min(vexRT[Ch2], 110);
    }

    else if (vexRT[Ch2] < -20) {
     	tmp = max(vexRT[Ch2], -110);
    }
    motor[DriveLeft1] = tmp * con;
    motor[DriveRight1] = 0.55*tmp * con;
    motor[DriveRight2] = 0.55*tmp * con;
    motor[DriveLeft2] = tmp * con;

    // Left axle turn
    if (vexRT[Btn5U]) {
      motor[DriveLeft1] = vexRT[Btn5U] * 90 * con;
      motor[DriveRight1] = vexRT[Btn5U] * -90 * con;
      motor[DriveRight2] = vexRT[Btn5U] * -90 * con;
      motor[DriveLeft2] = vexRT[Btn5U] * 90 * con;
    }
    // Right axle turn
    else if (vexRT[Btn6U]) {
      motor[DriveLeft1] = vexRT[Btn6U] * 90 * -con;
      motor[DriveRight1] = vexRT[Btn6U] * -90 * -con;
      motor[DriveRight2] = vexRT[Btn6U] * -90 * -con;
      motor[DriveLeft2] = vexRT[Btn6U] * 90 * -con;
    }



    // Turn left sensitive
    if (vexRT[Btn7L]) {
			motor[DriveLeft1] = 40 * con;
      motor[DriveRight1] = -40 * con;
      motor[DriveRight2] = -40 * con;
      motor[DriveLeft2] = 40 * con;
    }

    // Turn right sensitive
    else if (vexRT[Btn7R]) {
      motor[DriveLeft1] = 40 * -con;
      motor[DriveRight1] = -40 * -con;
      motor[DriveRight2] = -40 * -con;
      motor[DriveLeft2] = 40 * -con;
    }


    // Turn on the flywheel
    if (vexRT[Btn8U]) {
      int res = vexRT[Btn8U];
      motor[Flywheel1] = motor[Flywheel2] = res * 127 * -con;
      motor[Flywheel3] = res * -127 * -con;
    }
    else {
    	StopShoot();
  	}

    // Turn off the flywheel
    if (vexRT[Btn8D]) {
    	StopShoot();
  	}

    // Ball intake (CW) working
    if (vexRT[Btn6D]) {
      motor[Intake] = vexRT[Btn6D] * -100 * con;
    }

    // Ball intake (CCW) working
    else if (vexRT[Btn5D]) {
      motor[Intake] = vexRT[Btn5D] * 100 * con;
    }

    else {
      StopBallIntake();
    }

    // Implement indexer and (maybe) 3rd intake here...
		if (vexRT[Btn7U]) {
			motor[Indexer] = vexRT[Btn7U] * -100 * con;
		}
		else if (vexRT[Btn7D]) {
			motor[Indexer] = vexRT[Btn7D] * 100 * con;
		}
		else {
			StopBallIndexer();
		}

		// For auto shoot (top 2 flags)
		if (vexRT[Btn8L]) {
			autoShoot();
		}

		// For turning 90 degrees CW
		if (vexRT[Btn8R]) {
			Turn90R();
		}
  }
}
