#pragma config(Motor,  port2,           DriveLeft1,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DriveLeft2,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DriveRight1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DriveRight2,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Shooter,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Intake1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Intake2,       tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                        */
/*      Description: Competition template for VEX EDR                   */
/*                                                                        */
/*---------------------------------------------------------------------------*/
// This code is for the VEX cortex platform
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
//Global Helper Functions
int min(int a,int b)
{
  if(b<a)
      return b;
  return a;
}
int max(int a,int b)
{
  if(b>a)
      return b;
  return a;
}
//Global variables
const int dev = -10; //This is the global deviation
int con = -1; // This variable to to be used as conventional direction
bool stop_intake; // For stopping ball-intake

/*---------------------------------------------------------------------------*/
/*                        Pre-Autonomous Functions                      */
/*                                                                        */
/*  You may want to perform some actions before the competition starts.   */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This    */
/*  function is only called once after the cortex has been powered on and */
/*  not every time that the robot is disabled.                            */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
  // Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
  // used by the competition include file, for example, you might want
  // to display your team name on the LCD in this function.
  // bDisplayCompetitionStatusOnLcd = false;
  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
  return;
}
/*---------------------------------------------------------------------------*/
/*                                                                        */
/*                            Autonomous Task                           */
/*                                                                        */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                    */
/*                                                                        */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
//Autonomous Functions
//Drive forward
void DriveF(int amount, int time)
{
  int tmp = min(vexRT[Ch2],100);
  motor[DriveLeft1]= tmp*con;
  motor[DriveRight1] = tmp*con-dev;
  motor[DriveRight2] = tmp*con-dev;
  motor[DriveLeft2]= tmp*con;
  if(time !=0) wait1Msec(time);
}

//Drive backwards
void DriveB(int amount, int time)
{
  amount = -amount;
  int tmp = max(vexRT[Ch2],-100);
  motor[DriveLeft1]= tmp*con;
  motor[DriveRight1] = tmp*con-dev;
  motor[DriveRight2] = tmp*con-dev;
  motor[DriveLeft2]= tmp*con;
  if(time != 0 ) wait1Msec(time);
}

// Turn right
void TurnR (int amount, int time) {
  motor[DriveLeft1]= vexRT[Btn6U]*amount*-con;
  motor[DriveLeft2]= vexRT[Btn6U]*amount*-con;
  motor[DriveRight1] = vexRT[Btn6U]*-amount*-con;
  motor[DriveRight2] = vexRT[Btn6U]*-amount*-con;
  if(time != 0 ) wait1Msec(time);
}

// Turn left
void TurnL (int amount, int time) {
  motor[DriveLeft1]= amount*con;
  motor[DriveLeft2]= amount*con;
  motor[DriveRight1] = -amount*con;
  motor[DriveRight2] = -amount*con;
  if(time != 0 ) wait1Msec(time);
}

// Rotate the claw, any direction doesn't matter, it will still flip the object
void RotateClaw1 (int amount, int time) {
  motor[Claw] = amount*con;
  if(time != 0 ) wait1Msec(time);
}

void RotateClaw2 (int amount, int time) {
  motor[Claw] = amount*-con;
  if(time != 0 ) wait1Msec(time);
}

// For taking ball in
void BallIntake (int amount, int time) {
  motor[Intake1] = -amount*con;
  motor[Intake2] = -amount*con;
  if(time != 0 )wait1Msec(time);
}

// For shooting the ball. The gear will only rotate one direction throughout, rewinding and launching too
void Shoot (int amount, int time) {
  motor[Shooter] = amount*con;
  if(time != 0 ) wait1Msec(time);
}


// For stopping the drive
void StopDrive () {
  motor[DriveLeft1] = 0;
  motor[DriveRight1] = 0;
  motor[DriveRight2] = 0;
  motor[DriveLeft2] = 0;
}

// For stopping the claw angle
void StopClawAngle () {
  motor[Claw] = 0;
}

// For stopping the shooter
void StopShoot () {
  motor[Shooter] = 0;
}



void autoNoFlag()
{

}


task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................
  // Remove this function call once you have "real" code.


}
/*---------------------------------------------------------------------------*/
/*                                                                        */
/*                            User Control Task                         */
/*                                                                        */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                    */
/*                                                                        */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
  // User control code here, inside the loop
  while (1)
  {
        //FORWARD AND BACKWARD
        int tmp;
          if(vexRT[Ch2] > 0){
              tmp = min(vexRT[Ch2],100);}
          else if(vexRT[Ch2] <0){
              tmp = max(vexRT[Ch2],-100);}
          motor[DriveLeft1] = tmp*con;
          motor[DriveRight1] = tmp*con-dev;
          motor[DriveRight2] = tmp*con-dev;
          motor[DriveLeft2] = tmp*con;
      if(vexRT[Btn5U])
      {
      //Left axle turn
          motor[DriveLeft1] = vexRT[Btn5U]*127*con;
          motor[DriveLeft2] = vexRT[Btn5U]*127*con;
          motor[DriveRight1] = vexRT[Btn5U]*-127*con;
          motor[DriveRight2] = vexRT[Btn5U]*-127*con;
      }
      if (vexRT[Btn6U])
      {
      //Right axle turn
          motor[DriveLeft1] = vexRT[Btn6U]*127*-con;
          motor[DriveLeft2] = vexRT[Btn6U]*127*-con;
          motor[DriveRight1] = vexRT[Btn6U]*-127*-con;
          motor[DriveRight2] = vexRT[Btn6U]*-127*-con;
      }

      // Claw angle rotation (CCW) not working - need to replace motor most likely
     if(vexRT[Btn7U])
      {
          motor[Claw] = vexRT[Btn7U]*127*-con;
      }
      if(!vexRT[Btn7U])
      {
            motor[Claw] = 0;
      }
      // Claw angle rotation (CW) working
      if(vexRT[Btn7L])
      {
          motor[Claw] = vexRT[Btn7L]*127*con;
      }
      if(!vexRT[Btn7L])
      {
            motor[Claw] = 0;
      }

      /* Need to make sure catapult arm stays in place - Use a potentiometer!!! */
      // Shooter working CCW (make sure it goes back down again after shooting up)
      if(vexRT[Btn8L])
      {
          int res = vexRT[Btn8L];
          motor[Shooter] = res*127*-con;
          wait1Msec(1500);
          motor[Shooter] = 0;
          // motor[Shooter] = res*30*con;
      }
      // Shooter working CW (make sure it goes back down again after shooting up)
      if(vexRT[Btn8R])
      {
          int res = vexRT[Btn8R];
          motor[Shooter] = res*127*con;
          wait1Msec(1500);
          // motor[Shooter] = res*30*-con;
      }

      // Ball intake (CCW) not working - hardware problem
      if(vexRT[Btn6D])
      {
          motor[Intake1] = vexRT[Btn6D]*-127*con;
          motor[Intake2] = vexRT[Btn6D]*-127*-con;
          stop_intake = 1;
      }
      if(!vexRT[Btn6D])
      {
          motor[Intake1] = motor[Intake2] = 0;
      }
      // Ball intake (CW) working
      if(vexRT[Btn5D])
      {
          motor[Intake1] = vexRT[Btn5D]*127*con;
          motor[Intake2] = vexRT[Btn5D]*127*-con;
          stop_intake = 1;
      }
      if(!vexRT[Btn5D])
      {
          motor[Intake1] = motor[Intake2] = 0;
      }
  }
}
